#!/usr/bin/env python3
"""Zero-dependency catalog generator for mind-palace-agent-skills.

Reads every skills/<name>/SKILL.md frontmatter and skill-rules.json, then writes
docs/CATALOG.md grouped into the two suites (Memory Palace / Blessing).

Usage:
  python scripts/generate_catalog.py           # write docs/CATALOG.md
  python scripts/generate_catalog.py --check    # exit 1 if CATALOG.md is stale
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SKILLS_DIR = ROOT / "skills"
CATALOG = ROOT / "docs" / "CATALOG.md"

# The two suites and the skills that belong to each, in presentation order.
MEMORY_SUITE = [
    "palace-foundations", "memory-palace-architect", "loci-encoder", "number-memory",
    "palace-walk", "spaced-recall", "imagination-gym", "agent-memory-palace", "palace-visualizer",
]
BLESSING_SUITE = ["github-bless", "weekly-blessing", "palace-build", "blessing-standard"]


def read_description(skill: str) -> str:
    path = SKILLS_DIR / skill / "SKILL.md"
    if not path.exists():
        return "(missing)"
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        return ""
    end = text.find("\n---", 3)
    block = text[3 : end if end != -1 else len(text)].splitlines()
    for line in block:
        if line.startswith("description:"):
            return line.partition(":")[2].strip()
    return ""


def render() -> str:
    lines: list[str] = []
    lines.append("# Skills Catalog")
    lines.append("")
    lines.append("_Generated by `python scripts/generate_catalog.py` — do not edit by hand._")
    lines.append("")
    discovered = {p.parent.name for p in SKILLS_DIR.glob("*/SKILL.md")}
    grouped = set(MEMORY_SUITE) | set(BLESSING_SUITE)

    def table(title: str, blurb: str, skills: list[str]) -> None:
        present = [s for s in skills if s in discovered]
        lines.append(f"## {title}")
        lines.append("")
        lines.append(blurb)
        lines.append(f"_{len(present)} skills_")
        lines.append("")
        lines.append("| Skill | What it does |")
        lines.append("|---|---|")
        for s in present:
            lines.append(f"| [`{s}`](../skills/{s}/SKILL.md) | {read_description(s)} |")
        lines.append("")

    table("Memory Palace suite",
          "The method of loci for humans and agents — design, encode, recall, schedule, render.",
          MEMORY_SUITE)
    table("Blessing suite",
          "The [Blessing Protocol](https://github.com/frankxai/bless) — witness the week, grow a palace from what is whole.",
          BLESSING_SUITE)

    ungrouped = sorted(discovered - grouped)
    if ungrouped:
        table("Other", "Skills not yet assigned to a suite.", ungrouped)

    lines.append("---")
    lines.append("")
    lines.append("Built on SIP · mind-palace-agent-skills")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    content = render()
    check = "--check" in sys.argv[1:]
    if check:
        current = CATALOG.read_text(encoding="utf-8") if CATALOG.exists() else ""
        if current != content:
            print("FAIL — docs/CATALOG.md is stale. Run: python scripts/generate_catalog.py")
            return 1
        print("OK — docs/CATALOG.md is up to date")
        return 0
    CATALOG.parent.mkdir(parents=True, exist_ok=True)
    CATALOG.write_text(content, encoding="utf-8")
    print(f"OK — wrote {CATALOG.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
